name: Release Fedora

on:
  push:
    branches: [ fedora ]
  pull_request:

jobs:
  build-job:
    runs-on: ubuntu-latest # TODO: change to self-hosted on macOS or benefit for public repository
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello from Fedora ðŸ‘‹"
      - run: pwd
      - run: ls -la
