name: Release macOS

on:
  push:
    branches: [ macos ]
  pull_request:

jobs:
  build-job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello from macOS ðŸ‘‹"
      - run: pwd
      - run: ls -la
