name: Release Ubuntu

on:
  push:
    branches: [ ubuntu ]
  pull_request:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello from Ubuntu ðŸ‘‹"
      - run: pwd
      - run: ls -la
