name: Release Windows

on:
  push:
    branches: [ windows ]
  pull_request:

jobs:
  build-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello from Windows ðŸ‘‹"
      - run: pwd
      - run: dir
